<a href="https://colab.research.google.com/github/maxhart5000/ML-NLP-Bag-Of-Words/blob/main/natural_language_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Natural Language Processing

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
dataset = pd.read_csv('Restaurant_Reviews.tsv', delimiter = '\t', quoting = 3)

## Cleaning the texts

In [ ]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []

ps = PorterStemmer()
all_stopwords = stopwords.words('english')
all_stopwords.remove('not')

for i in range(0, 1000):
  review = re.sub('[^a-zA-Z]', ' ', dataset['Review'][i])
  review = review.lower()
  review = review.split()
  review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
  review = ' '.join(review)
  corpus.append(review)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


## Creating the Bag of Words model

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500)
X = cv.fit_transform(corpus).toarray()
y = dataset.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state  = 0)

## Training the Naive Bayes model on the Training set

In [ ]:
from sklearn.naive_bayes import GaussianNB
naive_bayes = GaussianNB()
naive_bayes.fit(X_train, y_train)

GaussianNB()

## Training the KNN model on the Training set


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
knn.fit(X_train, y_train)

KNeighborsClassifier()

## Training the Kernel SVM (linear) model on the Training set

In [ ]:
from sklearn.svm import SVC
kernel_svm = SVC(kernel = 'rbf', random_state = 0)
kernel_svm.fit(X_train, y_train)

SVC(random_state=0)

## Training the Random Forest model on the Training set

In [ ]:
from sklearn.ensemble import RandomForestClassifier
random_forest = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
random_forest.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

## Predicting the Test set results with Naive Bayes model

In [ ]:
y_pred_naive_bayes = naive_bayes.predict(X_test)
# print(np.concatenate((y_pred_naive_bayes.reshape(len(y_pred_naive_bayes),1), y_test.reshape(len(y_test),1)),1))

## Predicting the Test set results with KNN model

In [ ]:
y_pred_knn = knn.predict(X_test)
# print(np.concatenate((y_pred_knn.reshape(len(y_pred_knn),1), y_test.reshape(len(y_test),1)),1))

## Predicting the Test set results with Kernel SVM model


In [ ]:
y_pred_kernel_svm = kernel_svm.predict(X_test)

## Predicting the Test set results with Random Forest model

In [ ]:
y_pred_random_forest = random_forest.predict(X_test)

## Making the Confusion Matrix - Naive Bayes model

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_naive_bayes)
print(cm)
accuracy_score(y_test, y_pred_naive_bayes)

[[55 42]
 [12 91]]


0.73

## Making the Confusion Matrix - KNN model

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_knn)
print(cm)
accuracy_score(y_test, y_pred_knn)

[[68 29]
 [42 61]]


0.645

## Making the Confusion Matrix - Kernel SVM


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_kernel_svm)
print(cm)
accuracy_score(y_test, y_pred_kernel_svm)

[[89  8]
 [36 67]]


0.78

## Making the Confusion Matrix - Random Forest


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_random_forest)
print(cm)
accuracy_score(y_test, y_pred_random_forest)

[[87 10]
 [45 58]]


0.725